# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protobuf import auth_pb2 as protobuf_dot_auth__pb2


class AUTHStub(object):
    """定义可以被远程调用的函数
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AuthLogin = channel.stream_stream(
                '/auth.AUTH/AuthLogin',
                request_serializer=protobuf_dot_auth__pb2.Request.SerializeToString,
                response_deserializer=protobuf_dot_auth__pb2.Response.FromString,
                )


class AUTHServicer(object):
    """定义可以被远程调用的函数
    """

    def AuthLogin(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AUTHServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AuthLogin': grpc.stream_stream_rpc_method_handler(
                    servicer.AuthLogin,
                    request_deserializer=protobuf_dot_auth__pb2.Request.FromString,
                    response_serializer=protobuf_dot_auth__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'auth.AUTH', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AUTH(object):
    """定义可以被远程调用的函数
    """

    @staticmethod
    def AuthLogin(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/auth.AUTH/AuthLogin',
            protobuf_dot_auth__pb2.Request.SerializeToString,
            protobuf_dot_auth__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
